replicaCount: 2

image:
  repository: emqx/emqx
  tag: 5.6.0

service:
  type: ClusterIP
  ports:
    mqtt: 1883
    mqttssl: 8883
    dashboard: 18083

env:
  EMQX_NAME: emqx
  EMQX_CLUSTER__DISCOVERY: dns
  EMQX_CLUSTER__DNS__NAME: emqx-headless.iot.svc.cluster.local

  # TLS
  EMQX_LISTENERS__SSL__DEFAULT__ENABLED: "true"
  EMQX_LISTENERS__SSL__DEFAULT__BIND: "0.0.0.0:8883"

  # Auth
  EMQX_AUTHENTICATION__1__MECHANISM: password_based
  EMQX_AUTHENTICATION__1__BACKEND: built_in_database

  # ACL
  EMQX_AUTHORIZATION__SOURCES__1__TYPE: file
  EMQX_AUTHORIZATION__SOURCES__1__PATH: "/opt/emqx/etc/acl.conf"

persistence:
  enabled: true
  size: 10Gi
  storageClass: default
