image:
  repository: lldap/lldap
  tag: 2026-03-04-alpine
  pullPolicy: IfNotPresent

config:
  ldapPort: 3890
  httpPort: 17170
  baseDn: "dc=home,dc=cluster"
  adminUser: "admin"

persistence:
  enabled: true
  storageClass: default
  size: 1Gi

namespace:
  labels:
    project-name: "home-cluster"
    stage: "prod"
