namespace:
  labels:
    project-name: "home-cluster"
    stage: "prod"

multus:
  image:
    repository: ghcr.io/k8snetworkplumbingwg/multus-cni
    tag: v4.1.0
  config:
    cniVersion: "0.3.1"
    # The default CNI to delegate to (k3s uses flannel or canal)
    defaultNetworkName: "flannel" 
