apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: iot-platform
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: prod

  template:
    metadata:
      name: 'iot-{{env}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/saumya/home-platform-engg-devops-n100-services-runtime
        targetRevision: 'master'
        path: environments/{{env}}/iot

      destination:
        server: https://kubernetes.default.svc
        namespace: iot

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
