apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saumya/home-platform-engg-devops-n100-services-runtime
    targetRevision: master
    path: environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
