namespace:
  labels:
    project-name: "home-cluster"
    stage: "prod"

velero:
  configuration:
    provider: aws
    backupStorageLocation:
      - name: default
        bucket: velero
        provider: aws
        config:
          region: minio
          s3ForcePathStyle: true
          s3Url: http://192.168.1.10:9000
      - name: offsite
        bucket: velero-backups
        provider: aws
        config:
          region: auto
          s3ForcePathStyle: true
          s3Url: https://YOUR_ACCOUNT_ID.r2.cloudflarestorage.com
    volumeSnapshotLocation:
      name: default
      config:
        region: minio
  credentials:
    existingSecret: velero-minio-credentials
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.11.0
      volumeMounts:
        - mountPath: /plugins
          name: plugins
