apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-storage-class
  annotations:
    policies.kyverno.io/title: Inject Storage Class based on Hardware
    policies.kyverno.io/description: Automatically swaps "default" storage class with the hardware-specific one.
spec:
  rules:
    - name: mutate-storage-class
      match:
        any:
          - resources:
              kinds:
                - PersistentVolumeClaim
      mutate:
        patchStrategicMerge:
          spec:
            (storageClassName): "default"
            storageClassName: {{ .Values.global.storageClass | default "local-path" | quote }} # This will be managed by Kubara config
